version: "3.7"

services:
  shinkan:
    image: shinkan-server
    build:
      context: .
      dockerfile: cmd/api/Dockerfile
    ports:
      - 8080:8080
    env_file: [./cmd/api/.env]
    container_name: shinkan-server
    networks:
      - services

networks:
  services:
    external:
      name: db_shinkan_network
