name: Go
on: [push]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps:

    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: MySQL setup
      run: |
        mysql --host 127.0.0.1 --port 3306 -uroot -proot < ./db/init/test_ddl.sql
        mysql --host 127.0.0.1 --port 3306 -uroot -proot < ./db/init/test_dml.sql
    - name: Test
      run: go test -cover ./...

